# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

# 日本語コメントを許可
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 50

RSpec/ContextWording:
  Enabled: false

RSpec/LetSetup:
  Enabled: false